apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: copier-update-test
  annotations:
    github.com/project-slug: super-awesome-org/copier-update-test
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: backstage
